### ISSUE TITLE
[not an issue] Are there any videos recording of the course?

### ISSUE THREAD

**Issue by Reoooh** [johnnychen94/Julia_and_its_applications#2]
冒昧打搅了非常抱歉。
请问课程是否有录像？作为新手非常想听一下。
另外感谢您的jill.py🙏。

**Comment by johnnychen94** [comment]
这次系列讲座不打算录制视频或者之类的东西，主要是因为这些内容之前都没有准备过材料，所以更希望能够在线下一边讲一边交流的方式把内容完善好。明年可能会考虑组织成更正式一些的材料，比如说视频、或者技术文档。

如果看材料的过程中有任何相关的问题（无论是覆盖到的还是没有覆盖到的），也都可以发 issue 来询问
